import enum


class PenaltyType(enum.IntEnum):
    REGULARIZE = 0
    LEFT_FOOT_CONTACT = 1
    RIGHT_FOOT_CONTACT = 2
    COM_HEIGHT = 3
    COM_PROJECTED_SUPPORT_POLYGON = 4
    LEFT_FOOT_CONTACT_END = 5
    RIGHT_FOOT_CONTACT_END = 6
    COM_VEL_END = 7
    COM_HEIGHT_END = 8
    POSE = 9

    COM_IN_LEFT_FOOT = 10
    COM_IN_RIGHT_FOOT = 11
    COM_IN_LEFT_FOOT_END = 12
    COM_IN_RIGHT_FOOT_END = 13

    COM_IN_HEAD = 14

    MAX_Y_ANGULAR_MOMENTUM = 15

    MAX_Y_VELOCITY_END = 16
    MAX_Y_ANGULAR_MOMENTUM_END = 17

    MAX_Y_POS_DIFF_END = 18

    TORQUE = 19
