import enum


class PenaltyType(enum.IntEnum):
    REGULARIZE = 0
    LEFT_FOOT_CONTACT = 1
    RIGHT_FOOT_CONTACT = 2
    COM_HEIGHT = 3
    COM_PROJECTED_SUPPORT_POLYGON = 4
    LEFT_FOOT_CONTACT_END = 5
    RIGHT_FOOT_CONTACT_END = 6
    COM_VEL_END = 7
    COM_HEIGHT_END = 8
    POSE = 9

    COM_IN_LEFT_FOOT = 10
    COM_IN_RIGHT_FOOT = 11
    COM_IN_LEFT_FOOT_END = 12
    COM_IN_RIGHT_FOOT_END = 13

    COM_IN_HEAD = 14

    MAX_Y_ANGULAR_MOMENTUM = 15

    MAX_Y_VELOCITY_END = 16
    MAX_Y_ANGULAR_MOMENTUM_END = 17

    MAX_Y_POS_DIFF_END = 18

    TORQUE = 19

    COM_VEL = 20
    PELVIS_HEADING = 21
    PELVIS_HEADING_END = 22

    COM_IN_LEFT_FOOT_TOE = 23
    COM_IN_RIGHT_FOOT_TOE = 24
    LEFT_FOOT_TOE_CONTACT = 25
    RIGHT_FOOT_TOE_CONTACT = 26
    COM_IN_LEFT_FOOT_TOE_END = 27
    COM_IN_RIGHT_FOOT_TOE_END = 28
    LEFT_FOOT_TOE_CONTACT_END = 29
    RIGHT_FOOT_TOE_CONTACT_END = 30

    COM_IN_LEFT_RIGHT_CENTER = 31
    COM_IN_LEFT_RIGHT_CENTER_END = 32

    COM_VEL_DIR_WITH_PELVIS_LOCAL = 33

    MAX_Y_LEFT_FOOT_HEEL = 34
    MAX_Y_LEFT_FOOT_HEEL_END = 35
    MAX_Y_RIGHT_FOOT_HEEL = 36
    MAX_Y_RIGHT_FOOT_HEEL_END = 37

    MAX_Y_RIGHT_TOE_HEAD_DIFF = 38
